/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    IconTablerSearch: typeof import('~icons/tabler/search')['default']
    RouterHome: typeof import('./components/RouterHome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadcnDemo: typeof import('./components/ShadcnDemo.vue')['default']
  }
}
